# -- 主菜单 --
# 主菜单显示在页面顶部的页眉中。
# 可接受的参数为 name、pageRef、page、url、title、weight。
#
# 最简单的菜单配置如下：
#   name = 在此菜单链接中显示的名称
#   pageRef = 要链接的页面或部分的标识符
#
# 默认情况下，菜单按字母顺序排列。可以通过提供 weight 值覆盖此行为。菜单将按 weight 从低到高排序。


[[main]]
  name = "关于"
  pageRef = "about"
  weight = 10

[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "友链"
  pageRef = "friends"
  weight = 30

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- 页脚菜单 --
# 页脚菜单显示在页面底部，版权说明之前。
# 配置方式与上面的主菜单相同。


[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
